# Generated by Django 4.2.13 on 2024-05-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ucitel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(max_length=30)),
                ('priezvisko', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('heslo', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Ucitel',
                'verbose_name_plural': 'Ucitelia',
                'ordering': ['priezvisko'],
            },
        ),
    ]
