# Generated by Django 4.2.13 on 2024-05-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odbor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo', models.IntegerField(max_length=3)),
                ('nazov', models.CharField(max_length=30)),
                ('popis', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Odbor',
                'verbose_name_plural': 'Odbori',
                'ordering': ['cislo'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meno', models.CharField(max_length=30)),
                ('priezvisko', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('heslo', models.CharField(max_length=30)),
                ('trieda', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Studenti',
                'ordering': ['priezvisko'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=60)),
                ('popis', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='ucitel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
