# Generated by Django 4.2.5 on 2024-06-06 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0003_alter_tema_options_tema_conzultant_tema_dostupnost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dostupnost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Dostupnosť',
                'verbose_name_plural': 'Dostupnosť',
            },
        ),
        migrations.AlterModelOptions(
            name='tema',
            options={'ordering': ['dostupnost'], 'verbose_name': 'Tema', 'verbose_name_plural': 'Temy'},
        ),
        migrations.AlterField(
            model_name='tema',
            name='conzultant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='soc.ucitel'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='odbor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='soc.odbor'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='dostupnost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='soc.dostupnost'),
        ),
    ]
