# Generated by Django 4.2.13 on 2024-06-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0004_dostupnost_alter_tema_options_alter_tema_conzultant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='odbor',
            options={'verbose_name': 'Odbor', 'verbose_name_plural': 'Odbori'},
        ),
        migrations.RemoveField(
            model_name='odbor',
            name='cislo',
        ),
        migrations.RemoveField(
            model_name='odbor',
            name='popis',
        ),
        migrations.AlterField(
            model_name='odbor',
            name='nazov',
            field=models.CharField(max_length=60),
        ),
    ]
