# Generated by Django 4.2.7 on 2024-06-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0005_alter_odbor_options_remove_odbor_cislo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tema',
            options={'ordering': ['dostupnost_id', 'nazov'], 'verbose_name': 'Tema', 'verbose_name_plural': 'Temy'},
        ),
        migrations.AlterField(
            model_name='odbor',
            name='nazov',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='tema',
            name='nazov',
            field=models.CharField(max_length=100),
        ),
    ]
